version: '3'

services:
  app:
    container_name: nest_container
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    networks:
      - app-network

  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: <PROJECT NAME>
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
  app:
